{\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fcharset204{\*\fname Arial;}Arial CYR;}}
{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20 <?xml version="1.0" ?>\par
<!DOCTYPE Course_Catalog[\par
<!ELEMENT Course_Catalog (Department)*>\par
<!ELEMENT Department (Title | Chair | Course)*>\par
<!ATTLIST Department Code CDATA #REQUIRED>\par
<!ELEMENT Title (#PCDATA)>                                        \par
<!ELEMENT Chair (Professor)?>\par
<!ELEMENT Professor ((First_Name) | (Middle_Initial) | (Last_Name))*>\par
<!ELEMENT First_Name (#PCDATA)> \par
<!ELEMENT Last_Name (#PCDATA)>\par
<!ELEMENT Middle_Initial (#PCDATA)>\par
<!ELEMENT Course (Title | Description | Instructors | Prerequisites)*>\par
<!ATTLIST Course Number CDATA #REQUIRED \par
                 Enrollment CDATA #IMPLIED>\par
<!ELEMENT Description (#PCDATA)>             \par
<!ELEMENT Instructors (Lecturer | Professor)*>\par
<!ELEMENT Prerequisites (Prereq)*>\par
<!ELEMENT Prereq (#PCDATA)>\par
<!ELEMENT Lecturer (First_Name | Middle_Initial | Last_Name)*>\par
]>\par
<Course_Catalog>\par
\par
  <Department Code="CS">\par
    \par
    <Title>Computer Science</Title>\par
    \par
    <Chair>\par
      <Professor>\par
        <First_Name>Jennifer</First_Name>\par
        <Last_Name>Widom</Last_Name>\par
      </Professor>\par
    </Chair>\par
\par
    <Course Number="CS106A" Enrollment="1070">\par
      <Title>Programming Methodology</Title>\par
      <Description>Introduction to the engineering of computer applications emphasizing modern software engineering principles.</Description>\par
      <Instructors>\par
        <Lecturer>\par
          <First_Name>Jerry</First_Name>\par
          <Middle_Initial>R.</Middle_Initial>\par
          <Last_Name>Cain</Last_Name>\par
        </Lecturer>\par
        <Professor>\par
          <First_Name>Eric</First_Name>\par
          <Last_Name>Roberts</Last_Name>\par
        </Professor>\par
        <Professor>\par
          <First_Name>Mehran</First_Name>\par
          <Last_Name>Sahami</Last_Name>\par
        </Professor>\par
      </Instructors>\par
    </Course>\par
    \par
    <Course Number="CS106B" Enrollment="620">\par
      <Title>Programming Abstractions</Title>\par
      <Description>Abstraction and its relation to programming.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Eric</First_Name>\par
          <Last_Name>Roberts</Last_Name>\par
        </Professor>\par
        <Lecturer>\par
          <First_Name>Jerry</First_Name>\par
          <Middle_Initial>R.</Middle_Initial>\par
          <Last_Name>Cain</Last_Name>\par
        </Lecturer>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS106A</Prereq>\par
      </Prerequisites>\par
    </Course>\par
    \par
    <Course Number="CS107" Enrollment="500">\par
      <Title>Computer Organization and Systems</Title>\par
      <Description>Introduction to the fundamental concepts of computer systems.</Description>\par
      <Instructors>\par
        <Lecturer>\par
          <First_Name>Julie</First_Name>\par
          <Last_Name>Zelenski</Last_Name>\par
        </Lecturer>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS106B</Prereq>\par
      </Prerequisites>\par
    </Course>    \par
  \par
    <Course Number="CS109" Enrollment="280">\par
      <Title>Introduction to Probability for Computer Scientists</Title>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Mehran</First_Name>\par
          <Last_Name>Sahami</Last_Name>\par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS106B</Prereq>\par
      </Prerequisites>      \par
    </Course>\par
\par
    <Course Number="CS124" Enrollment="60">\par
      <Title>From Languages to Information</Title>\par
      <Description>Natural language processing. Cross-listed as LING180.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Dan</First_Name>\par
          <Last_Name>Jurafsky</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS107</Prereq>\par
        <Prereq>CS109</Prereq>\par
      </Prerequisites>   \par
    </Course>\par
\par
    <Course Number="CS143" Enrollment="90">\par
      <Title>Compilers</Title>\par
      <Description>Principles and practices for design and implementation of compilers and interpreters.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Alex</First_Name>\par
          <Middle_Initial>S.</Middle_Initial>\par
          <Last_Name>Aiken</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS107</Prereq>\par
      </Prerequisites>   \par
    </Course>\par
    \par
    <Course Number="CS145" Enrollment="130">\par
      <Title>Introduction to Databases</Title>\par
      <Description>Database design and use of database management systems for applications.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Jennifer</First_Name>\par
          <Last_Name>Widom</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS107</Prereq>\par
      </Prerequisites>  \par
    </Course>\par
\par
    <Course Number="CS221" Enrollment="180">\par
      <Title>Artificial Intelligence: Principles and Techniques</Title>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Andrew</First_Name>\par
          <Last_Name>Ng</Last_Name>    \par
        </Professor>\par
        <Professor>\par
          <First_Name>Sebastian</First_Name>\par
          <Last_Name>Thrun</Last_Name>    \par
        </Professor>        \par
      </Instructors>\par
    </Course>\par
    \par
    <Course Number="CS228" Enrollment="110">\par
      <Title>Structured Probabilistic Models: Principles and Techniques</Title>\par
      <Description>Using probabilistic modeling languages to represent complex domains.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Daphne</First_Name>\par
          <Last_Name>Koller</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
    </Course>\par
\par
    <Course Number="CS229" Enrollment="320">\par
      <Title>Machine Learning</Title>\par
      <Description>A broad introduction to machine learning and statistical pattern recognition.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Andrew</First_Name>\par
          <Last_Name>Ng</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
    </Course>\par
\par
  </Department>\par
\par
  <Department Code="EE">\par
  \par
    <Title>Electrical Engineering</Title>\par
    \par
    <Chair>\par
      <Professor>\par
        <First_Name>Mark</First_Name>\par
        <Middle_Initial>A.</Middle_Initial>\par
        <Last_Name>Horowitz</Last_Name>\par
      </Professor>    \par
    </Chair>\par
  \par
    <Course Number="EE108A">\par
      <Title>Digital Systems I</Title>\par
      <Description>Digital circuit, logic, and system design.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Subhasish</First_Name>\par
          <Last_Name>Mitra</Last_Name>\par
        </Professor>\par
      </Instructors>\par
    </Course>\par
    \par
    <Course Number="EE108B">\par
      <Title>Digital Systems II</Title>\par
      <Description>The design of processor-based digital systems.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>William</First_Name>\par
          <Middle_Initial>J.</Middle_Initial>\par
          <Last_Name>Dally</Last_Name>\par
        </Professor>      \par
        <Professor>\par
          <First_Name>Oyekunle</First_Name>\par
          <Last_Name>Olukotun</Last_Name>\par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>EE108A</Prereq>\par
        <Prereq>CS106B</Prereq>\par
      </Prerequisites>\par
    </Course>    \par
  \par
  </Department>\par
\par
  <Department Code="LING">\par
  \par
    <Title>Linguistics</Title>\par
    \par
    <Chair>    \par
      <Professor>\par
        <First_Name>Beth</First_Name>\par
        <Last_Name>Levin</Last_Name>    \par
      </Professor>\par
    </Chair>\par
\par
    <Course Number="LING180" Enrollment="60">\par
      <Title>From Languages to Information</Title>\par
      <Description>Natural language processing. Cross-listed as CS124.</Description>\par
      <Instructors>\par
        <Professor>\par
          <First_Name>Dan</First_Name>\par
          <Last_Name>Jurafsky</Last_Name>    \par
        </Professor>\par
      </Instructors>\par
      <Prerequisites>\par
        <Prereq>CS107</Prereq>\par
        <Prereq>CS109</Prereq>\par
      </Prerequisites>   \par
    </Course>\par
    \par
  </Department>\par
  \par
</Course_Catalog>\par
}
 